# Generated by Django 5.0.1 on 2024-02-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_ingrdient_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='w', max_length=50),
            preserve_default=False,
        ),
    ]
